language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: HBDKi/oESrqC0kbahWa6L866QNzSbWGF0hpPnCdysM7NOtAkiN9cPt5FQIPkHbiV6pmQPmLXP+Ql1tggh08QbVXI3P5tffnLIoUXW+LdCNhVIIua3dLz85AE+AHHlb1rPuv8kH5t2h4h/g/lxQzx8KthpZTJHAFIff7fgKpyKrR9VDys3jOMS3itGByrLgQBfD7cx1g/9Qyp8irzgwhZ5ii2PqtfnnBRmAQz8aewXlOVTw7/ViGD+2yqGVCEbr94tGOTkY4N0rZ3/YfGF6RsIko1pU4Oknol7yXOKGvdZNoqd09TwH1CFIatGjtwoTU00BY+VNKAU78aI+8Tc9Yr4WipehNb+uAHhxLXL7vkmZWYE4ePGHUmXNL011fYIqn6Fa2SqYa70ps/YAQTqVgUWus8LPzU6da+49Hxk+Qpn/4GEi1biLGpL5MxV0zDMvTRz+yK3n4zQWq1w2GPXW/5Q2xKqp9QdOGjwkbBBem5Jgda3p6T5ctuoxSuC/90xHtmtkNsnykI/0HBTr5He/+qD7dUrRI9Sq4hU3rE2YaB9NgNpwsDIlTNaVQ8aMiIdBrBj1DmGIxoC3slOEA45FZA1tdJ1nUkxAkVKSceNKMS90C/v6fTc1et0E4hYdFxRgJDlUL7WGghZblUVRJuH4v3eiCP0n7gMVc59Y7Kae34kIU=
  app: secret-earth-13004
  on:
    repo: ispoljari/react-hot-cold-app
branches:
  only:
  - master
